apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-demo
  namespace: default
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  selector:
    matchLabels:
      app: app-demo
  template:
    metadata:
      labels:
        app: app-demo
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - app-demo
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: app-demo
        image: asia-southeast1-docker.pkg.dev/PROJECT_ID/k8s-demo-docker/app-demo:IMAGE_PLACEHOLDER
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: app-demo-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: app-demo
  ports:
  - port: 80
    targetPort: 5000
