apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-demo
  namespace: default
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  selector:
    matchLabels:
      app: app-demo
  template:
    metadata:
      labels:
        app: app-demo
    spec:
      initContainers:
      - name: wait-for-postgres
        image: postgres:15
        command:
        - sh
        - -c
        - |
          until pg_isready -h postgres.default.svc.cluster.local -p 5432 -U demo; do
            echo "Waiting for postgres..."
            sleep 2
          done
      containers:
      - name: app-demo
        image: asia-southeast1-docker.pkg.dev/PROJECT_ID/k8s-demo-docker/app-demo:IMAGE_PLACEHOLDER
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: postgres.default.svc.cluster.local
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: demo
        - name: DB_USER
          value: demo
        - name: DB_PASS
          value: demo
---
apiVersion: v1
kind: Service
metadata:
  name: app-demo-service
  namespace: default
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: app-demo
  ports:
  - port: 80
    targetPort: 5000
