name: Deploy App

on:
  workflow_dispatch: 

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [v1, v2, v3]
    
    steps:
    - name: code checkout
      uses: actions/checkout@v3

    - name: install the gcloud cli
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GOOGLE_PROJECT }}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        install_components: 'gke-gcloud-auth-plugin'
        export_default_credentials: true

    - name: build and push the docker image
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      run: |
        gcloud auth configure-docker asia-southeast1-docker.pkg.dev
        docker build -t asia-southeast1-docker.pkg.dev/$GOOGLE_PROJECT/k8s-demo-docker/app-demo:latest .
        docker push asia-southeast1-docker.pkg.dev/$GOOGLE_PROJECT/k8s-demo-docker/app-demo:latest
