name: Deploy via Deployment YAML

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Select which version to deploy'
        required: true
        type: choice
        options:
          - v1
          - v2
          - v3
        default: v1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v3'
        with:
          install_components: 'gke-gcloud-auth-plugin'

      - name: Get GKE credentials
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER }} \
            --zone ${{ secrets.GKE_ZONE }} \
            --project $GOOGLE_PROJECT

      - name: Update deployment.yaml with selected version
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
          VERSION: ${{ github.event.inputs.version }}
        run: |
          sed -i "s|IMAGE_PLACEHOLDER|asia-southeast1-docker.pkg.dev/$GOOGLE_PROJECT/k8s-demo-docker/app-demo:${{ github.event.inputs.version }}|g" ./deployment.yaml

      - name: Apply manifest to GKE
        run: |
          kubectl apply -f ./deployment.yaml
          kubectl rollout status deployment/app-demo -n default
